typedef enum {
    ARMOR_TYPE_LIGHT = 0,
	ARMOR_TYPE_MEDIUM = 1,
	ARMOR_TYPE_HEAVY = 2,
	ARMOR_TYPE_FORTIFIED = 3,
	ARMOR_TYPE_NORMAL = 4,
	ARMOR_TYPE_HERO = 5,
	ARMOR_TYPE_DIVINE = 6,
    ARMOR_TYPE_UNARMORED = 7
} ArmorType;
