typedef enum {
    ATTACK_TYPE_NORMAL = 0,
    ATTACK_TYPE_MELEE = 1,
	ATTACK_TYPE_PIERCE = 2,
	ATTACK_TYPE_SIEGE = 3,
	ATTACK_TYPE_MAGIC = 4,
	ATTACK_TYPE_CHAOS = 5,
    ATTACK_TYPE_HERO = 6
} AttackType;
