typedef enum {
    ITEM_TYPE_PERMANENT = 0,
    ITEM_TYPE_CHARGED = 1,
    ITEM_TYPE_POWERUP = 2,
    ITEM_TYPE_ARTIFACT = 3,
    ITEM_TYPE_PURCHASABLE = 4,
    ITEM_TYPE_CAMPAIGN = 5,
    ITEM_TYPE_MISCELLANEOUS = 6,
    ITEM_TYPE_UNKNOWN = 7,
    ITEM_TYPE_ANY = 8
} ItemType;
