// basic stuff
#include "CharArray.h"
#include "StringArray.h"
#include "Vector2.h"
#include "Vector3.h"

// advanced stuff
#include "AbilDataCacheNode.h"
#include "AbilityLevelData.h"
#include "AbilityUIDef.h"

// advanced game stuff
#include "CAgent.h"
#include "CTriggerRegion.h" // : CAgent
#include "CGhostImage.h" // : CAgent
#include "CCreepCampUI.h" // : CAgent
#include "CCreepCampIndicator.h" // : CAgent
#include "CSplashData.h" // : CAgent
#include "MineShaft.h" // : CAgent
#include "AcolyteRingSlot.h" // : CAgent
#include "CRallyPoint.h" // : CAgent
#include "CAgentWar3.h" // : CAgent
  #include "CWar3Image.h" // : CAgentWar3
    #include "CEffectImage.h" // : CWar3Image
      #include "CEffectImagePos.h" // : CEffectImage
        #include "CEffectFlameStrikeTwo.h" // : CEffectImagePos
        #include "CEffectVolcano.h" // : CEffectImagePos
        #include "CBaseEffectDetector.h" // : CEffectImagePos
          #include "CEffectFlare.h" // : CBaseEffectDetector
        #include "CEffectRangeListener.h" // : CEffectImagePos
          #include "CEffectCloudOfFog.h" // : CEffectRangeListener
          #include "CEffectTranquility.h" // : CEffectRangeListener
            #include "CEffectStarfall.h" // : CEffectTranquility
              #include "CEffectMonsoon.h" // : CEffectStarfall
            #include "CEffectDeathAndDecay.h" // : CEffectTranquility
              #include "CEffectFlameStrike.h" // : CEffectDeathAndDecay
                #include "CEffectBallsOfFire.h" // : CEffectFlameStrike
          #include "CEffectClusterRockets.h" // : CEffectRangeListener
            #include "CEffectHealingSpray.h" // : CEffectClusterRockets
      #include "CEffectImageFogged.h" // : CEffectImage
    #include "CWidget.h" // : CWar3Image
      #include "CSelectable.h" // : CWidget
        #include "CDestructable.h" // : CSelectable
        #include "CUnit.h" // : CSelectable
        #include "CItem.h" // : CSelectable
      #include "CCaptainAI.h" // : CWidget
    #include "CBulletBase.h" // : CWar3Image
      #include "CBullet.h" // : CBulletBase
        #include "CMissileSentinel.h" // : CBullet
        #include "CMissileCarrionSwarm.h" // : CBullet
          #include "CMissileShockwave.h" // : CMissileCarrionSwarm
          #include "CMissileBreathOfFire.h" // : CMissileCarrionSwarm
            #include "CMissileBreathOfFrost.h" // : CMissileBreathOfFire
        #include "CMissileDarkSummoning.h" // : CBullet
        #include "CMissileStampede.h" // : CBullet
        #include "CMissile.h" // : CBullet
          #include "CMissileFire.h" // : CMissile
          #include "CMissileFeedback.h" // : CMissile
          #include "CMissileThunderBolt.h" // : CMissile
          #include "CMissileUnstableConcoction.h" // : CMissile
          #include "CMissileChainLightning.h" // : CMissile
          #include "CMissileMirrorImage.h" // : CMissile
          #include "CMissileCorrosiveBreath.h" // : CMissile
          #include "CMissileAbsorb.h" // : CMissile
          #include "CMissileDevourMagic.h" // : CMissile
          #include "CMissilePossession.h" // : CMissile
          #include "CMissileDeathCoil.h" // : CMissile
          #include "CMissileElementalFury.h" // : CMissile
          #include "CMissileLavaMonster.h" // : CMissile
          #include "CMissileSplash.h" // : CMissile
            #include "CMissileBallsOfFire.h" // : CMissileSplash
            #include "CMissileCorrosiveBreathSplash.h" // : CMissileSplash
            #include "CMissileFrostBreath.h" // : CMissileSplash
            #include "CBuffMissileSplash.h" // : CMissileSplash
              #include "CMissileFreezeSplash.h" // : CBuffMissileSplash
              #include "CMissileFrostSplash.h" // : CBuffMissileSplash
              #include "CMissilePoisonAttackSplash.h" // : CBuffMissileSplash
                #include "CMissileSlowPoisonSplash.h" // : CMissilePoisonAttackSplash
                #include "CMissileColdArrowSplash.h" // : CMissilePoisonAttackSplash
                #include "CMissilePoisonDamageSplash.h" // : CMissilePoisonAttackSplash
              #include "CMissileLiquidFireSplash.h" // : CBuffMissileSplash
              #include "CMissileCriticalStrikeSplash.h" // : CBuffMissileSplash
              #include "CMissileFreezingBreathSplash.h" // : CBuffMissileSplash
              #include "CMissileDrunkenHaze.h" // : CBuffMissileSplash
              #include "CMissileAcidBomb.h" // : CBuffMissileSplash
              #include "CMissileTransmute.h" // : CBuffMissileSplash
              #include "CMissileIncinerate.h" // : CBuffMissileSplash
              #include "CMissileCorruptionSplash.h" // : CBuffMissileSplash
              #include "CMissileLightningPurgeSplash.h" // : CBuffMissileSplash
              #include "CMissileSpellEffectSplash.h" // : CBuffMissileSplash
          #include "CMissileBounce.h" // : CMissile
            #include "CMissileItemDispelChain.h" // : CMissileBounce
          #include "CMissileLine.h" // : CMissile
          #include "CBuffMissile.h" // : CMissile
            #include "CMissileFreeze.h" // : CBuffMissile
            #include "CMissileFrost.h" // : CBuffMissile
            #include "CMissilePoisonAttack.h" // : CBuffMissile
              #include "CMissileSlowPoison.h" // : CMissilePoisonAttack
                #include "CMissileShadowStrike.h" // : CMissileSlowPoison
              #include "CMissileColdArrow.h" // : CMissilePoisonAttack
              #include "CMissileParasite.h" // : CMissilePoisonAttack
              #include "CMissilePoisonDamage.h" // : CMissilePoisonAttack
            #include "CMissilePhoenixFire.h" // : CBuffMissile
            #include "CMissileSpellSteal.h" // : CBuffMissile
            #include "CMissileThunderBoltTwo.h" // : CBuffMissile
            #include "CMissileEnsnare.h" // : CBuffMissile
            #include "CMissileLiquidFire.h" // : CBuffMissile
            #include "CMissileCriticalStrike.h" // : CBuffMissile
            #include "CMissileFreezingBreath.h" // : CBuffMissile
            #include "CMissileWeb.h" // : CBuffMissile
            #include "CMissileBlackArrow.h" // : CBuffMissile
            #include "CMissileCorruption.h" // : CBuffMissile
            #include "CMissileLightningPurge.h" // : CBuffMissile
            #include "CMissileSpellEffect.h" // : CBuffMissile
        #include "CArtillery.h" // : CBullet
          #include "CArtilleryFragShards.h" // : CArtillery
          #include "CArtilleryBallsOfFire.h" // : CArtillery
          #include "CArtilleryFrostBreath.h" // : CArtillery
          #include "CArtilleryPlagueToss.h" // : CArtillery
          #include "CArtilleryClusterRockets.h" // : CArtillery
          #include "CMissileSummonFactory.h" // : CArtillery
          #include "CArtilleryLine.h" // : CArtillery
          #include "CBuffArtillery.h" // : CArtillery
            #include "CArtilleryVolcano.h" // : CBuffArtillery
      #include "CBulletPath.h" // : CBulletBase
        #include "CMissilePath.h" // : CBulletPath
          #include "CMissileSpiderAttack.h" // : CMissilePath
    #include "CTrackable.h" // : CWar3Image
  #include "CUnitRefList.h" // : CAgentWar3
    #include "CTask.h" // : CUnitRefList
      #include "CTaskParam.h" // : CTask
        #include "CTaskOrderParam.h" // : CTaskParam
          #include "CTaskGhost.h" // : CTaskOrderParam
        #include "CTaskAction.h" // : CTaskParam
      #include "CTaskPoint.h" // : CTask
        #include "CTaskPoint2.h" // : CTaskPoint
        #include "CTaskPointAndTarget.h" // : CTaskPoint
      #include "CTaskTarget.h" // : CTask
        #include "CTaskTarget2.h" // : CTaskTarget
      #include "CTaskRotate.h" // : CTask
    #include "CAbility.h" // : CUnitRefList
      #include "CAbilityInterfaced.h" // : CAbility
        #include "CPower.h" // : CAbilityInterfaced
          #include "CAbilityButton.h" // : CPower
            #include "CAbilitySpell.h" // : CAbilityButton
              #include "CAbilitySimpleSpell.h" // : CAbilitySpell
                #include "CAbilityClosestTargetSpell.h" // : CAbilitySimpleSpell
                  #include "CAbilityAncestralSpirit.h" // : CAbilityClosestTargetSpell
                  #include "CAbilityCoupleInstant.h" // : CAbilityClosestTargetSpell
                  #include "CAbilityCannibalize.h" // : CAbilityClosestTargetSpell
                #include "CAbilityModalSpell.h" // : CAbilitySimpleSpell
                  #include "CAbilityAutoTargetSpell.h" // : CAbilityModalSpell
                    #include "CAbilityRepair.h" // : CAbilityAutoTargetSpell
                      #include "CAbilityRenew.h" // : CAbilityRepair
                      #include "CAbilityRestoration.h" // : CAbilityRepair
                    #include "CAbilitySelfDestruct.h" // : CAbilityAutoTargetSpell
                    #include "CAbilityHeal.h" // : CAbilityAutoTargetSpell
                      #include "CAbilityNeutralHeal.h" // : CAbilityHeal
                    #include "CAbilityInnerFire.h" // : CAbilityAutoTargetSpell
                    #include "CAbilitySlow.h" // : CAbilityAutoTargetSpell
                    #include "CAbilitySpellSteal.h" // : CAbilityAutoTargetSpell
                    #include "CAbilityRangerArrow.h" // : CAbilityAutoTargetSpell
                      #include "CAbilityFlamingArrows.h" // : CAbilityRangerArrow
                        #include "CAbilityFlamingAttack.h" // : CAbilityFlamingArrows
                        #include "CAbilityBlackArrow.h" // : CAbilityFlamingArrows
                      #include "CAbilityPoisonArrows.h" // : CAbilityRangerArrow
                      #include "CAbilityColdArrows.h" // : CAbilityRangerArrow
                      #include "CAbilityIncinerateArrow.h" // : CAbilityRangerArrow
                    #include "CAbilityBloodlust.h" // : CAbilityAutoTargetSpell
                      #include "CAbilityFrenzy.h" // : CAbilityBloodlust
                    #include "CAbilityAutoDispelMagic.h" // : CAbilityAutoTargetSpell
                    #include "CAbilityFaerieFire.h" // : CAbilityAutoTargetSpell
                    #include "CAbilityManaBattery.h" // : CAbilityAutoTargetSpell
                    #include "CAbilityCurse.h" // : CAbilityAutoTargetSpell
                    #include "CAbilityMeatLoad.h" // : CAbilityAutoTargetSpell
                    #include "CAbilityRaiseDead.h" // : CAbilityAutoTargetSpell
                      #include "CAbilityCarrionScarabs.h" // : CAbilityRaiseDead
                        #include "CAbilityVengeance.h" // : CAbilityCarrionScarabs
                      #include "CAbilityItemRaiseDead.h" // : CAbilityRaiseDead
                    #include "CAbilityReplenish.h" // : CAbilityAutoTargetSpell
                      #include "CAbilityReplenishLife.h" // : CAbilityReplenish
                      #include "CAbilityReplenishMana.h" // : CAbilityReplenish
                    #include "CAbilityWeb.h" // : CAbilityAutoTargetSpell
                    #include "CAbilityFrostArmorAuto.h" // : CAbilityAutoTargetSpell
                    #include "CAbilityParasite.h" // : CAbilityAutoTargetSpell
                  #include "CAbilityPhaseShift.h" // : CAbilityModalSpell
                  #include "CAbilityBarkskin.h" // : CAbilityModalSpell
                #include "CAbilityBlightPlacement.h" // : CAbilitySimpleSpell
                #include "CAbilityCargoDrop.h" // : CAbilitySimpleSpell
                #include "CAbilityCargoLoad.h" // : CAbilitySimpleSpell
                  #include "CAbilityDevour.h" // : CAbilityCargoLoad
                    #include "CAbilityCreepDevour.h" // : CAbilityDevour
                #include "CAbilityDetectAoe.h" // : CAbilitySimpleSpell
                  #include "CAbilityFarSight.h" // : CAbilityDetectAoe
                #include "CAbilityControlMagic.h" // : CAbilitySimpleSpell
                #include "CAbilityDispelMagic.h" // : CAbilitySimpleSpell
                  #include "CAbilityDisenchant.h" // : CAbilityDispelMagic
                  #include "CAbilityDetonate.h" // : CAbilityDispelMagic
                  #include "CAbilityItemDispelAoe.h" // : CAbilityDispelMagic
                #include "CAbilityFlare.h" // : CAbilitySimpleSpell
                #include "CAbilityInvisibility.h" // : CAbilitySimpleSpell
                #include "CAbilityMagicLeash.h" // : CAbilitySimpleSpell
                #include "CAbilityPolymorph.h" // : CAbilitySimpleSpell
                  #include "CAbilityHex.h" // : CAbilityPolymorph
                #include "CAbilityTankLoadPilot.h" // : CAbilitySimpleSpell
                #include "CAbilityTankPilot.h" // : CAbilitySimpleSpell
                #include "CAbilityBanish.h" // : CAbilitySimpleSpell
                #include "CAbilityBlizzard.h" // : CAbilitySimpleSpell
                  #include "CAbilityRainOfFire.h" // : CAbilityBlizzard
                #include "CAbilityDrain.h" // : CAbilitySimpleSpell
                #include "CAbilityEarthquake.h" // : CAbilitySimpleSpell
                #include "CAbilityFlameStrike.h" // : CAbilitySimpleSpell
                #include "CAbilityHolyBolt.h" // : CAbilitySimpleSpell
                #include "CAbilityMassTeleport.h" // : CAbilitySimpleSpell
                #include "CAbilityThunderBolt.h" // : CAbilitySimpleSpell
                  #include "CAbilityCreepThunderBolt.h" // : CAbilityThunderBolt
                  #include "CAbilityFireBolt.h" // : CAbilityThunderBolt
                #include "CAbilityEnsnare.h" // : CAbilitySimpleSpell
                #include "CAbilityEvilEye.h" // : CAbilitySimpleSpell
                #include "CAbilityHealingWard.h" // : CAbilitySimpleSpell
                #include "CAbilityLightningShield.h" // : CAbilitySimpleSpell
                #include "CAbilityPurge.h" // : CAbilitySimpleSpell
                  #include "CAbilityCargoHoldDeath.h" // : CAbilityPurge
                  #include "CAbilityLightningPurge.h" // : CAbilityPurge
                #include "CAbilitySpiritLink.h" // : CAbilitySimpleSpell
                #include "CAbilityStasisTrap.h" // : CAbilitySimpleSpell
                #include "CAbilityUnstableConcoction.h" // : CAbilitySimpleSpell
                #include "CAbilityChainLightning.h" // : CAbilitySimpleSpell
                  #include "CAbilityHealingWave.h" // : CAbilityChainLightning
                #include "CAbilityVoodoo.h" // : CAbilitySimpleSpell
                #include "CAbilityWard.h" // : CAbilitySimpleSpell
                  #include "CAbilityItemMonsterLure.h" // : CAbilityWard
                #include "CAbilityCyclone.h" // : CAbilitySimpleSpell
                #include "CAbilityDecouple.h" // : CAbilitySimpleSpell
                #include "CAbilityEatTree.h" // : CAbilitySimpleSpell
                  #include "CAbilityGrabTree.h" // : CAbilityEatTree
                #include "CAbilityManaFlare.h" // : CAbilitySimpleSpell
                #include "CAbilityRejuvination.h" // : CAbilitySimpleSpell
                  #include "CAbilityRegeneration.h" // : CAbilityRejuvination
                #include "CAbilitySentinel.h" // : CAbilitySimpleSpell
                #include "CAbilityTaunt.h" // : CAbilitySimpleSpell
                #include "CAbilityBlink.h" // : CAbilitySimpleSpell
                #include "CAbilityEntanglingRoots.h" // : CAbilitySimpleSpell
                #include "CAbilityFanOfKnives.h" // : CAbilitySimpleSpell
                #include "CAbilityForceOfNature.h" // : CAbilitySimpleSpell
                #include "CAbilityManaBurn.h" // : CAbilitySimpleSpell
                #include "CAbilityShadowStrike.h" // : CAbilitySimpleSpell
                #include "CAbilityAbsorb.h" // : CAbilitySimpleSpell
                #include "CAbilityAntiMagicShell.h" // : CAbilitySimpleSpell
                  #include "CAbilityAntiMagicShellInstant.h" // : CAbilityAntiMagicShell
                #include "CAbilityCripple.h" // : CAbilitySimpleSpell
                #include "CAbilityDevourMagic.h" // : CAbilitySimpleSpell
                #include "CAbilityExhume.h" // : CAbilitySimpleSpell
                #include "CAbilityPossession.h" // : CAbilitySimpleSpell
                  #include "CAbilityPossessionTwo.h" // : CAbilityPossession
                #include "CAbilitySacrificialLamb.h" // : CAbilitySimpleSpell
                #include "CAbilityUnholyFrenzy.h" // : CAbilitySimpleSpell
                #include "CAbilityUnsummon.h" // : CAbilitySimpleSpell
                #include "CAbilityAnimateDead.h" // : CAbilitySimpleSpell
                  #include "CAbilityResurrection.h" // : CAbilityAnimateDead
                    #include "CAbilityItemResurrection.h" // : CAbilityResurrection
                  #include "CAbilityCreepAnimateDead.h" // : CAbilityAnimateDead
                  #include "CAbilityItemAnimateDead.h" // : CAbilityAnimateDead
                #include "CAbilityCarrionSwarm.h" // : CAbilitySimpleSpell
                  #include "CAbilityShockwave.h" // : CAbilityCarrionSwarm
                  #include "CAbilityBreathOfFire.h" // : CAbilityCarrionSwarm
                    #include "CAbilityBreathOfFrost.h" // : CAbilityBreathOfFire
                #include "CAbilityDarkRitual.h" // : CAbilitySimpleSpell
                  #include "CAbilityDeathPact.h" // : CAbilityDarkRitual
                  #include "CAbilitySteal.h" // : CAbilityDarkRitual
                #include "CAbilityDarkSummoning.h" // : CAbilitySimpleSpell
                #include "CAbilityDeathAndDecay.h" // : CAbilitySimpleSpell
                #include "CAbilityDeathCoil.h" // : CAbilitySimpleSpell
                #include "CAbilityFrostArmor.h" // : CAbilitySimpleSpell
                #include "CAbilityFrostNova.h" // : CAbilitySimpleSpell
                  #include "CAbilityThunderClap.h" // : CAbilityFrostNova
                    #include "CAbilityStomp.h" // : CAbilityThunderClap
                    #include "CAbilityCreepThunderClap.h" // : CAbilityThunderClap
                #include "CAbilityImpale.h" // : CAbilitySimpleSpell
                #include "CAbilityLocustSwarm.h" // : CAbilitySimpleSpell
                #include "CAbilitySleep.h" // : CAbilitySimpleSpell
                  #include "CAbilityDarkConversion.h" // : CAbilitySleep
                #include "CAbilityMindRot.h" // : CAbilitySimpleSpell
                #include "CAbilityMonsoon.h" // : CAbilitySimpleSpell
                #include "CAbilityPreservation.h" // : CAbilitySimpleSpell
                  #include "CAbilitySanctuary.h" // : CAbilityPreservation
                #include "CAbilityShadowSight.h" // : CAbilitySimpleSpell
                #include "CAbilitySpellShield.h" // : CAbilitySimpleSpell
                  #include "CAbilitySpellShieldAoe.h" // : CAbilitySpellShield
                #include "CAbilityBlackArrowSpell.h" // : CAbilitySimpleSpell
                #include "CAbilityCharm.h" // : CAbilitySimpleSpell
                #include "CAbilityDoom.h" // : CAbilitySimpleSpell
                #include "CAbilityElementalFury.h" // : CAbilitySimpleSpell
                #include "CAbilityForkedLightning.h" // : CAbilitySimpleSpell
                #include "CAbilityManaShield.h" // : CAbilitySimpleSpell
                #include "CAbilitySilence.h" // : CAbilitySimpleSpell
                  #include "CAbilityCloudOfFog.h" // : CAbilitySilence
                  #include "CAbilityDrunkenHaze.h" // : CAbilitySilence
                #include "CAbilityStampede.h" // : CAbilitySimpleSpell
                #include "CAbilityTornado.h" // : CAbilitySimpleSpell
                #include "CAbilityAcidBomb.h" // : CAbilitySimpleSpell
                #include "CAbilityTransmute.h" // : CAbilitySimpleSpell
                #include "CAbilityClusterRockets.h" // : CAbilitySimpleSpell
                  #include "CAbilityHealingSpray.h" // : CAbilityClusterRockets
                #include "CAbilitySummonFactory.h" // : CAbilitySimpleSpell
                #include "CAbilitySoulBurn.h" // : CAbilitySimpleSpell
                #include "CAbilityVolcano.h" // : CAbilitySimpleSpell
                #include "CAbilityBattleRoar.h" // : CAbilitySimpleSpell
                #include "CAbilityChannel.h" // : CAbilitySimpleSpell
                #include "CAbilityDarkPortal.h" // : CAbilitySimpleSpell
                #include "CAbilityFingerOfDeath.h" // : CAbilitySimpleSpell
                #include "CAbilityInferno.h" // : CAbilitySimpleSpell
                  #include "CAbilityDreadLordInferno.h" // : CAbilityInferno
                #include "CAbilityRainOfChaos.h" // : CAbilitySimpleSpell
                #include "CAbilitySoulPreservation.h" // : CAbilitySimpleSpell
                #include "CAbilityAttributeMod.h" // : CAbilitySimpleSpell
                  #include "CAbilityAgilityMod.h" // : CAbilityAttributeMod
                  #include "CAbilityIntelligenceMod.h" // : CAbilityAttributeMod
                  #include "CAbilityStrengthMod.h" // : CAbilityAttributeMod
                #include "CAbilityFigurine.h" // : CAbilitySimpleSpell
                  #include "CAbilityFigurineFurbolg.h" // : CAbilityFigurine
                  #include "CAbilityFigurineRedDrake.h" // : CAbilityFigurine
                  #include "CAbilityFigurineRockGolem.h" // : CAbilityFigurine
                  #include "CAbilityFigurineDoomGuard.h" // : CAbilityFigurine
                  #include "CAbilityFigurineFelHound.h" // : CAbilityFigurine
                  #include "CAbilityFigurineSkeleton.h" // : CAbilityFigurine
                #include "CAbilityTome.h" // : CAbilitySimpleSpell
                  #include "CAbilityAttackMod.h" // : CAbilityTome
                  #include "CAbilityExperienceMod.h" // : CAbilityTome
                  #include "CAbilityGlyph.h" // : CAbilityTome
                  #include "CAbilityLevelMod.h" // : CAbilityTome
                  #include "CAbilityMaxLifeMod.h" // : CAbilityTome
                  #include "CAbilityMaxManaMod.h" // : CAbilityTome
                  #include "CAbilityRebirth.h" // : CAbilityTome
                  #include "CAbilityItemGiveGold.h" // : CAbilityTome
                  #include "CAbilityItemGiveLumber.h" // : CAbilityTome
                #include "CAbilityItemCommand.h" // : CAbilitySimpleSpell
                #include "CAbilityItemDamageAoe.h" // : CAbilitySimpleSpell
                #include "CAbilityItemDefenseAoe.h" // : CAbilitySimpleSpell
                #include "CAbilityItemDetectAoe.h" // : CAbilitySimpleSpell
                #include "CAbilityItemHeal.h" // : CAbilitySimpleSpell
                #include "CAbilityItemHealAoe.h" // : CAbilitySimpleSpell
                #include "CAbilityItemIllusion.h" // : CAbilitySimpleSpell
                #include "CAbilityItemManaRestore.h" // : CAbilitySimpleSpell
                #include "CAbilityItemManaRestoreAoe.h" // : CAbilitySimpleSpell
                #include "CAbilityItemPlaceMine.h" // : CAbilitySimpleSpell
                #include "CAbilityItemRandomItem.h" // : CAbilitySimpleSpell
                #include "CAbilityItemRecall.h" // : CAbilitySimpleSpell
                #include "CAbilityItemRestore.h" // : CAbilitySimpleSpell
                #include "CAbilityItemRestoreAoe.h" // : CAbilitySimpleSpell
                #include "CAbilityItemSpeed.h" // : CAbilitySimpleSpell
                  #include "CAbilityItemSpeedAoe.h" // : CAbilityItemSpeed
                #include "CAbilityItemTeleport.h" // : CAbilitySimpleSpell
                  #include "CAbilityItemTownPortal.h" // : CAbilityItemTeleport
                #include "CAbilityItemInvis.h" // : CAbilitySimpleSpell
                #include "CAbilityItemInvul.h" // : CAbilitySimpleSpell
                #include "CAbilitySoulTrap.h" // : CAbilitySimpleSpell
                #include "CAbilityItemFlyingCarpet.h" // : CAbilitySimpleSpell
                #include "CAbilityItemVampirePotion.h" // : CAbilitySimpleSpell
                #include "CAbilityItemWeb.h" // : CAbilitySimpleSpell
                #include "CAbilityItemDispelChain.h" // : CAbilitySimpleSpell
                #include "CAbilityItemCureAoe.h" // : CAbilitySimpleSpell
                #include "CAbilityItemFlare.h" // : CAbilitySimpleSpell
                #include "CAbilityItemBuild.h" // : CAbilitySimpleSpell
                #include "CAbilityItemDetectByBuff.h" // : CAbilitySimpleSpell
              #include "CAbilityAuraSpell.h" // : CAbilitySpell
              #include "CAbilityBounce.h" // : CAbilitySpell
              #include "CAbilityCargoDropInstant.h" // : CAbilitySpell
                #include "CAbilityStandDown.h" // : CAbilityCargoDropInstant
                #include "CAbilityMeatDrop.h" // : CAbilityCargoDropInstant
              #include "CAbilityMorph.h" // : CAbilitySpell
                #include "CAbilityMount.h" // : CAbilityMorph
                #include "CAbilityPhoenix.h" // : CAbilityMorph
                #include "CAbilityCorporealForm.h" // : CAbilityMorph
                #include "CAbilityEtherealForm.h" // : CAbilityMorph
                #include "CAbilityBearForm.h" // : CAbilityMorph
                #include "CAbilityRavenForm.h" // : CAbilityMorph
                #include "CAbilityMetamorphosis.h" // : CAbilityMorph
                #include "CAbilityAvengerForm.h" // : CAbilityMorph
                #include "CAbilityBurrow.h" // : CAbilityMorph
                  #include "CAbilitySubmerge.h" // : CAbilityBurrow
                #include "CAbilityStoneForm.h" // : CAbilityMorph
                #include "CAbilityChemicalRage.h" // : CAbilityMorph
                #include "CAbilityRoboGoblin.h" // : CAbilityMorph
              #include "CAbilityRetrain.h" // : CAbilitySpell
              #include "CAbilityRevenge.h" // : CAbilitySpell
              #include "CAbilityTankDropPilot.h" // : CAbilitySpell
              #include "CAbilityAvatar.h" // : CAbilitySpell
              #include "CAbilityDivineShield.h" // : CAbilitySpell
              #include "CAbilityWaterElemental.h" // : CAbilitySpell
                #include "CAbilitySummonPhoenix.h" // : CAbilityWaterElemental
                #include "CAbilityScout.h" // : CAbilityWaterElemental
                #include "CAbilitySpiritOfVengeance.h" // : CAbilityWaterElemental
                #include "CAbilityMechanicalCritter.h" // : CAbilityWaterElemental
                #include "CAbilitySummonGrizzly.h" // : CAbilityWaterElemental
                #include "CAbilitySummonQuillbeast.h" // : CAbilityWaterElemental
                #include "CAbilitySummonWarEagle.h" // : CAbilityWaterElemental
                #include "CAbilityWateryMinion.h" // : CAbilityWaterElemental
                #include "CAbilityLavaMonster.h" // : CAbilityWaterElemental
              #include "CAbilityBattlestations.h" // : CAbilitySpell
              #include "CAbilityBerserkerRage.h" // : CAbilitySpell
              #include "CAbilityMirrorImage.h" // : CAbilitySpell
              #include "CAbilityReincarnation.h" // : CAbilitySpell
                #include "CAbilityCreepReincarnation.h" // : CAbilityReincarnation
              #include "CAbilitySpiritWolf.h" // : CAbilitySpell
                #include "CAbilitySpiritTroll.h" // : CAbilitySpiritWolf
              #include "CAbilityWhirlwind.h" // : CAbilitySpell
              #include "CAbilityWindWalk.h" // : CAbilitySpell
              #include "CAbilityRoar.h" // : CAbilitySpell
                #include "CAbilityHowlOfTerror.h" // : CAbilityRoar
              #include "CAbilityImmolation.h" // : CAbilitySpell
              #include "CAbilityTranquility.h" // : CAbilitySpell
                #include "CAbilityStarfall.h" // : CAbilityTranquility
              #include "CAbilitySpellBook.h" // : CAbilitySpell
              #include "CAbilityItemChangeTOD.h" // : CAbilitySpell
              #include "CAbilityItemRevealMap.h" // : CAbilitySpell
            #include "CAbilityNeutralSpell.h" // : CAbilityButton
              #include "CAbilityNeutralInteract.h" // : CAbilityNeutralSpell
              #include "CAbilityNeutralDetectAoe.h" // : CAbilityNeutralSpell
              #include "CAbilityNeutralG2L.h" // : CAbilityNeutralSpell
              #include "CAbilityNeutralL2G.h" // : CAbilityNeutralSpell
              #include "CAbilityNeutralSpies.h" // : CAbilityNeutralSpell
            #include "CAbilityPassive.h" // : CAbilityButton
              #include "CAbilityDetector.h" // : CAbilityPassive
                #include "CAbilityBurrowDetector.h" // : CAbilityDetector
                #include "CAbilityGyroVision.h" // : CAbilityDetector
                #include "CAbilityMagicSentry.h" // : CAbilityDetector
                #include "CAbilityTrueSight.h" // : CAbilityDetector
              #include "CAbilityPoisonAttack.h" // : CAbilityPassive
                #include "CAbilityVenomSpear.h" // : CAbilityPoisonAttack
                #include "CAbilitySlowPoison.h" // : CAbilityPoisonAttack
                #include "CAbilityPoisonDamage.h" // : CAbilityPoisonAttack
              #include "CAbilityBarrage.h" // : CAbilityPassive
              #include "CAbilityFeedback.h" // : CAbilityPassive
              #include "CAbilityFlakCannon.h" // : CAbilityPassive
              #include "CAbilityFragShards.h" // : CAbilityPassive
              #include "CAbilityGyroBombs.h" // : CAbilityPassive
              #include "CAbilityPhoenixFire.h" // : CAbilityPassive
              #include "CAbilityStormHammers.h" // : CAbilityPassive
              #include "CAbilityBallsOfFire.h" // : CAbilityPassive
              #include "CAbilityLiquidFire.h" // : CAbilityPassive
              #include "CAbilitySalvage.h" // : CAbilityPassive
              #include "CAbilityWarStomp.h" // : CAbilityPassive
                #include "CAbilityDemolish.h" // : CAbilityWarStomp
              #include "CAbilityCriticalStrike.h" // : CAbilityPassive
                #include "CAbilityBash.h" // : CAbilityCriticalStrike
                #include "CAbilityDrunkenBrawler.h" // : CAbilityCriticalStrike
              #include "CAbilityCorrosiveBreath.h" // : CAbilityPassive
              #include "CAbilityEthereal.h" // : CAbilityPassive
              #include "CAbilityImpalingBolt.h" // : CAbilityPassive
              #include "CAbilityMagicImmunity.h" // : CAbilityPassive
              #include "CAbilityMoonGlaive.h" // : CAbilityPassive
              #include "CAbilityResistantSkin.h" // : CAbilityPassive
              #include "CAbilityStoneSkin.h" // : CAbilityPassive
              #include "CAbilityEvasion.h" // : CAbilityPassive
              #include "CAbilityFreezingBreath.h" // : CAbilityPassive
              #include "CAbilityFrostAttack.h" // : CAbilityPassive
              #include "CAbilityPlagueToss.h" // : CAbilityPassive
              #include "CAbilityPermImmolation.h" // : CAbilityPassive
                #include "CAbilityPandaImmolation.h" // : CAbilityPermImmolation
                #include "CAbilityItemCloakOfFlames.h" // : CAbilityPermImmolation
              #include "CAbilityThorns.h" // : CAbilityPassive
                #include "CAbilityThornyShield.h" // : CAbilityThorns
              #include "CAbilityAttributeModSkill.h" // : CAbilityPassive
              #include "CAbilityCleavingAttack.h" // : CAbilityPassive
                #include "CAbilityIncinerate.h" // : CAbilityCleavingAttack
              #include "CAbilityEngineeringUpgrade.h" // : CAbilityPassive
              #include "CAbilityFactory.h" // : CAbilityPassive
              #include "CAbilityPassiveDefense.h" // : CAbilityPassive
            #include "CAbilityHide.h" // : CAbilityButton
            #include "CAbilityDefend.h" // : CAbilityButton
              #include "CAbilityMagicDefense.h" // : CAbilityDefend
            #include "CAbilityRoot.h" // : CAbilityButton
            #include "CAbilityShadowMeld.h" // : CAbilityButton
          #include "CAbilityAttack.h" // : CPower
          #include "CAbilityCargoHold.h" // : CPower
            #include "CAbilityBunker.h" // : CAbilityCargoHold
            #include "CAbilityDevourCargo.h" // : CAbilityCargoHold
            #include "CAbilityEntangleCargo.h" // : CAbilityCargoHold
            #include "CAbilityMeatCargo.h" // : CAbilityCargoHold
          #include "CAbilityHarvestBase.h" // : CPower
            #include "CAbilityHarvestReturn.h" // : CAbilityHarvestBase
              #include "CAbilityHarvestLumber.h" // : CAbilityHarvestReturn
                #include "CAbilityHarvest.h" // : CAbilityHarvestLumber
            #include "CAbilityWispHarvest.h" // : CAbilityHarvestBase
          #include "CAbilityMove.h" // : CPower
          #include "CAbilityCallToArms.h" // : CPower
            #include "CAbilityMilitia.h" // : CAbilityCallToArms
            #include "CAbilityMilitiaConvert.h" // : CAbilityCallToArms
          #include "CAbilityCouple.h" // : CPower
            #include "CAbilityCoupleArcher.h" // : CAbilityCouple
            #include "CAbilityCoupleHippogryph.h" // : CAbilityCouple
          #include "CAbilityEntangle.h" // : CPower
          #include "CAbilityAcolyteHarvest.h" // : CPower
        #include "CAbilityBaseBuild.h" // : CAbilityInterfaced
          #include "CAbilityBuildQueue.h" // : CAbilityBaseBuild
            #include "CAbilityTrain.h" // : CAbilityBuildQueue
              #include "CAbilitySacrifice.h" // : CAbilityTrain
            #include "CAbilityRevive.h" // : CAbilityBuildQueue
          #include "CAbilityBuild.h" // : CAbilityBaseBuild
            #include "CAbilityNeutralBuild.h" // : CAbilityBuild
              #include "CAbilityNightElfBuild.h" // : CAbilityNeutralBuild
              #include "CAbilityOrcBuild.h" // : CAbilityNeutralBuild
              #include "CAbilityNagaBuild.h" // : CAbilityNeutralBuild
            #include "CAbilityHumanBuild.h" // : CAbilityBuild
            #include "CAbilityUndeadBuild.h" // : CAbilityBuild
          #include "CAbilityBaseSell.h" // : CAbilityBaseBuild
            #include "CAbilitySellItem.h" // : CAbilityBaseSell
              #include "CAbilityMakeItem.h" // : CAbilitySellItem
              #include "CAbilitySellItemDynamic.h" // : CAbilitySellItem
            #include "CAbilitySellUnit.h" // : CAbilityBaseSell
              #include "CAbilitySellUnitDynamic.h" // : CAbilitySellUnit
          #include "CAbilityResearch.h" // : CAbilityBaseBuild
          #include "CAbilityQueue.h" // : CAbilityBaseBuild
          #include "CAbilityUpgrade.h" // : CAbilityBaseBuild
          #include "CAbilityInProgress.h" // : CAbilityBaseBuild
            #include "CAbilityBuildInProgress.h" // : CAbilityInProgress
            #include "CAbilityUpgradeInProgress.h" // : CAbilityInProgress
          #include "CAbilitySacrificeInProgress.h" // : CAbilityBaseBuild
        #include "CAbilityRally.h" // : CAbilityInterfaced
        #include "CAbilityHero.h" // : CAbilityInterfaced
        #include "CAbilityInventory.h" // : CAbilityInterfaced
        #include "CAbilityAwaken.h" // : CAbilityInterfaced
      #include "CBonusBase.h" // : CAbility
        #include "CBuff.h" // : CBonusBase
          #include "CBuffAura.h" // : CBuff
            #include "CBuffAuraBrilliance.h" // : CBuffAura
            #include "CBuffAuraDevotion.h" // : CBuffAura
            #include "CBuffAuraRegenLife.h" // : CBuffAura
            #include "CBuffAuraRegenMana.h" // : CBuffAura
            #include "CBuffAuraCommand.h" // : CBuffAura
              #include "CBuffAuraKotoBeast.h" // : CBuffAuraCommand
              #include "CBuffAuraTrueshot.h" // : CBuffAuraCommand
            #include "CBuffAuraEndurance.h" // : CBuffAura
              #include "CBuffAuraSlow.h" // : CBuffAuraEndurance
            #include "CBuffAuraThorns.h" // : CBuffAura
            #include "CBuffAuraBlightRegen.h" // : CBuffAura
            #include "CBuffAuraUnholy.h" // : CBuffAura
            #include "CBuffAuraVampiric.h" // : CBuffAura
          #include "CBuffDoT.h" // : CBuff
            #include "CBuffLifeDoT.h" // : CBuffDoT
              #include "CBuffPoisonAttack.h" // : CBuffLifeDoT
                #include "CBuffPoisonAttackStackDoT.h" // : CBuffPoisonAttack
                  #include "CBuffSlowPoisonStackDoT.h" // : CBuffPoisonAttackStackDoT
                  #include "CBuffPoisonDamageStackDoT.h" // : CBuffPoisonAttackStackDoT
                #include "CBuffLiquidFire.h" // : CBuffPoisonAttack
                #include "CBuffSlowPoison.h" // : CBuffPoisonAttack
                  #include "CBuffShadowStrike.h" // : CBuffSlowPoison
                #include "CBuffColdArrow.h" // : CBuffPoisonAttack
                  #include "CBuffColdArrowStackDoT.h" // : CBuffColdArrow
                #include "CBuffAcidBomb.h" // : CBuffPoisonAttack
                #include "CBuffParasite.h" // : CBuffPoisonAttack
                #include "CBuffPoisonDamage.h" // : CBuffPoisonAttack
              #include "CBuffMagicLeashTarget.h" // : CBuffLifeDoT
              #include "CBuffPhoenixFire.h" // : CBuffLifeDoT
              #include "CBuffBlizzard.h" // : CBuffLifeDoT
              #include "CBuffFlameStrike.h" // : CBuffLifeDoT
                #include "CBuffBallsOfFire.h" // : CBuffFlameStrike
              #include "CBuffDigesting.h" // : CBuffLifeDoT
              #include "CBuffCorrosiveBreath.h" // : CBuffLifeDoT
              #include "CBuffEntanglingRoots.h" // : CBuffLifeDoT
              #include "CBuffAuraPlague.h" // : CBuffLifeDoT
              #include "CBuffUnholyFrenzy.h" // : CBuffLifeDoT
              #include "CBuffUnsummon.h" // : CBuffLifeDoT
              #include "CBuffBreathOfFire.h" // : CBuffLifeDoT
                #include "CBuffBreathOfFrost.h" // : CBuffBreathOfFire
              #include "CBuffDoom.h" // : CBuffLifeDoT
              #include "CBuffRainOfFire.h" // : CBuffLifeDoT
          #include "CBuffManaDrain.h" // : CBuff
            #include "CBuffMindRot.h" // : CBuffManaDrain
          #include "CBuffPause.h" // : CBuff
            #include "CBuffPhaseShift.h" // : CBuffPause
            #include "CBuffPossession.h" // : CBuffPause
            #include "CBuffSleepPause.h" // : CBuffPause
            #include "CBuffTransmute.h" // : CBuffPause
          #include "CBuffProgressBar.h" // : CBuff
            #include "CBuffTimedLife.h" // : CBuffProgressBar
              #include "CBuffControlMagic.h" // : CBuffTimedLife
              #include "CBuffWaterElemental.h" // : CBuffTimedLife
                #include "CBuffSpiritOfVengeance.h" // : CBuffWaterElemental
                #include "CBuffMechanicalCritter.h" // : CBuffWaterElemental
                #include "CBuffSummonGrizzly.h" // : CBuffWaterElemental
                #include "CBuffSummonQuillbeast.h" // : CBuffWaterElemental
                #include "CBuffSummonWarEagle.h" // : CBuffWaterElemental
                #include "CBuffWateryMinion.h" // : CBuffWaterElemental
              #include "CBuffEvilEye.h" // : CBuffTimedLife
              #include "CBuffHealingWard.h" // : CBuffTimedLife
              #include "CBuffStasisTrapTrigger.h" // : CBuffTimedLife
              #include "CBuffMirrorImage.h" // : CBuffTimedLife
                #include "CBuffItemIllusion.h" // : CBuffMirrorImage
              #include "CBuffSpiritWolf.h" // : CBuffTimedLife
                #include "CBuffSpiritTroll.h" // : CBuffSpiritWolf
              #include "CBuffWard.h" // : CBuffTimedLife
                #include "CBuffItemMonsterLure.h" // : CBuffWard
              #include "CBuffForceOfNature.h" // : CBuffTimedLife
              #include "CBuffScout.h" // : CBuffTimedLife
              #include "CBuffPlagueWard.h" // : CBuffTimedLife
              #include "CBuffRaiseDead.h" // : CBuffTimedLife
                #include "CBuffCarrionScarab.h" // : CBuffRaiseDead
                  #include "CBuffVengeance.h" // : CBuffCarrionScarab
              #include "CBuffAnimateDead.h" // : CBuffTimedLife
              #include "CBuffDarkMinion.h" // : CBuffTimedLife
              #include "CBuffDoomMinion.h" // : CBuffTimedLife
              #include "CBuffElementalFury.h" // : CBuffTimedLife
              #include "CBuffTornado.h" // : CBuffTimedLife
              #include "CBuffClockworkGoblin.h" // : CBuffTimedLife
              #include "CBuffFactory.h" // : CBuffTimedLife
              #include "CBuffLavaMonster.h" // : CBuffTimedLife
              #include "CBuffInfernal.h" // : CBuffTimedLife
              #include "CBuffParasiteMinion.h" // : CBuffTimedLife
              #include "CBuffFigurine.h" // : CBuffTimedLife
              #include "CBuffRebirth.h" // : CBuffTimedLife
            #include "CBuffMilitia.h" // : CBuffProgressBar
            #include "CBuffPhoenix.h" // : CBuffProgressBar
            #include "CBuffPolymorph.h" // : CBuffProgressBar
              #include "CBuffHex.h" // : CBuffPolymorph
            #include "CBuffAvatar.h" // : CBuffProgressBar
            #include "CBuffMetamorphosis.h" // : CBuffProgressBar
            #include "CBuffChemicalRage.h" // : CBuffProgressBar
          #include "CBuffPulseReveal.h" // : CBuff
          #include "CBaseBuffInvulnerable.h" // : CBuff
            #include "CBuffInvulnerable.h" // : CBaseBuffInvulnerable
              #include "CBuffVoodoo.h" // : CBuffInvulnerable
          #include "CBuffSpeed.h" // : CBuff
            #include "CBuffEthereal.h" // : CBuffSpeed
              #include "CBuffBanish.h" // : CBuffEthereal
            #include "CBuffFrost.h" // : CBuffSpeed
            #include "CBuffSlow.h" // : CBuffSpeed
            #include "CBuffThunderClap.h" // : CBuffSpeed
              #include "CBuffCreepThunderClap.h" // : CBuffThunderClap
            #include "CBuffBerserkerRage.h" // : CBuffSpeed
            #include "CBuffBloodlust.h" // : CBuffSpeed
              #include "CBuffFrenzy.h" // : CBuffBloodlust
            #include "CBuffEarthquake.h" // : CBuffSpeed
            #include "CBuffSpeedBonus.h" // : CBuffSpeed
            #include "CBuffCripple.h" // : CBuffSpeed
              #include "CBuffSoulBurn.h" // : CBuffCripple
            #include "CBuffSilence.h" // : CBuffSpeed
              #include "CBuffCloudOfFog.h" // : CBuffSilence
              #include "CBuffDrunkenHaze.h" // : CBuffSilence
          #include "CBuffAoe.h" // : CBuff
            #include "CBuffBlizzardAoe.h" // : CBuffAoe
            #include "CBuffFlameStrikeAoe.h" // : CBuffAoe
            #include "CBuffLightningShieldAoe.h" // : CBuffAoe
            #include "CBuffEarthquakeAoe.h" // : CBuffAoe
            #include "CBuffWhirlwindAoe.h" // : CBuffAoe
            #include "CBuffManaFlareAoe.h" // : CBuffAoe
            #include "CBuffImmolationAoe.h" // : CBuffAoe
            #include "CBuffDeathAndDecayAoe.h" // : CBuffAoe
            #include "CBuffTornadoDamageAoe.h" // : CBuffAoe
            #include "CBuffTornadoSpinAoe.h" // : CBuffAoe
            #include "CBuffRainOfFireAoe.h" // : CBuffAoe
            #include "CBuffClusterRockets.h" // : CBuffAoe
              #include "CBuffHealingSpray.h" // : CBuffClusterRockets
            #include "CBuffVolcanoAoe.h" // : CBuffAoe
          #include "CBuffStackInfo.h" // : CBuff
            #include "CBuffPoisonAttackStackInfo.h" // : CBuffStackInfo
              #include "CBuffSlowPoisonStackInfo.h" // : CBuffPoisonAttackStackInfo
              #include "CBuffColdArrowStackInfo.h" // : CBuffPoisonAttackStackInfo
              #include "CBuffPoisonDamageStackInfo.h" // : CBuffPoisonAttackStackInfo
          #include "CBuffTarget.h" // : CBuff
          #include "CBuffDefense.h" // : CBuff
            #include "CBuffBarkskin.h" // : CBuffDefense
          #include "CBuffDetected.h" // : CBuff
            #include "CBuffStun.h" // : CBuffDetected
              #include "CBuffFreeze.h" // : CBuffStun
              #include "CBuffFreezingBreath.h" // : CBuffStun
              #include "CBuffSleepStun.h" // : CBuffStun
            #include "CBuffSharedVision.h" // : CBuffDetected
              #include "CBuffDevourVision.h" // : CBuffSharedVision
              #include "CBuffEnsnare.h" // : CBuffSharedVision
                #include "CBuffEnsnareAir.h" // : CBuffEnsnare
                  #include "CBuffWebAir.h" // : CBuffEnsnareAir
                #include "CBuffEnsnareGround.h" // : CBuffEnsnare
                  #include "CBuffWeb.h" // : CBuffEnsnareGround
              #include "CBuffFaerieFire.h" // : CBuffSharedVision
              #include "CBuffShadowSight.h" // : CBuffSharedVision
          #include "CBuffRangeListener.h" // : CBuff
            #include "CBuffManaFlare.h" // : CBuffRangeListener
          #include "CBuffHeal.h" // : CBuff
            #include "CBuffReplenish.h" // : CBuffHeal
              #include "CBuffReplenishLife.h" // : CBuffReplenish
              #include "CBuffReplenishMana.h" // : CBuffReplenish
          #include "CBuffInnerFire.h" // : CBuff
            #include "CBuffRoar.h" // : CBuffInnerFire
              #include "CBuffHowlOfTerror.h" // : CBuffRoar
              #include "CBuffBattleRoar.h" // : CBuffRoar
          #include "CBuffInvisibility.h" // : CBuff
            #include "CBuffWindWalk.h" // : CBuffInvisibility
          #include "CBuffMagicLeashCaster.h" // : CBuff
          #include "CBuffDivineShield.h" // : CBuff
          #include "CBuffDrainBonus.h" // : CBuff
            #include "CBuffDrainBonusLife.h" // : CBuffDrainBonus
            #include "CBuffDrainBonusMana.h" // : CBuffDrainBonus
          #include "CBuffDrainCaster.h" // : CBuff
            #include "CBuffDrainCasterLife.h" // : CBuffDrainCaster
            #include "CBuffDrainCasterMana.h" // : CBuffDrainCaster
            #include "CBuffDrainTarget.h" // : CBuffDrainCaster
              #include "CBuffDrainTargetLife.h" // : CBuffDrainTarget
              #include "CBuffDrainTargetMana.h" // : CBuffDrainTarget
          #include "CBuffLightningShield.h" // : CBuff
            #include "CBuffImmolation.h" // : CBuffLightningShield
              #include "CBuffPermImmolation.h" // : CBuffImmolation
                #include "CBuffPandaImmolation.h" // : CBuffPermImmolation
              #include "CBuffItemCloakOfFlames.h" // : CBuffImmolation
          #include "CBuffPurge.h" // : CBuff
            #include "CBuffCargoHoldDeath.h" // : CBuffPurge
          #include "CBuffSpiritLink.h" // : CBuff
          #include "CBuffVoodooCaster.h" // : CBuff
          #include "CBuffCyclone.h" // : CBuff
            #include "CBuffCycloneTwo.h" // : CBuffCyclone
              #include "CBuffImpale.h" // : CBuffCycloneTwo
              #include "CBuffTornadoSpin.h" // : CBuffCycloneTwo
          #include "CBuffGrabTree.h" // : CBuff
          #include "CBuffRejuvination.h" // : CBuff
            #include "CBuffEatTree.h" // : CBuffRejuvination
            #include "CBuffRegeneration.h" // : CBuffRejuvination
              #include "CBuffRegenLife.h" // : CBuffRegeneration
              #include "CBuffRegenMana.h" // : CBuffRegeneration
          #include "CBuffTaunt.h" // : CBuff
          #include "CBuffAntiMagicShell.h" // : CBuff
          #include "CBuffAntiMagicShellTwo.h" // : CBuff
          #include "CBuffCurse.h" // : CBuff
          #include "CBuffPossessionCaster.h" // : CBuff
          #include "CBuffSpiderAttack.h" // : CBuff
          #include "CBuffCarrionSwarm.h" // : CBuff
            #include "CBuffShockwave.h" // : CBuffCarrionSwarm
          #include "CBuffFrostArmor.h" // : CBuff
          #include "CBuffSleep.h" // : CBuff
            #include "CBuffDarkConversion.h" // : CBuffSleep
          #include "CBuffSanctuary.h" // : CBuff
          #include "CBuffSpellShield.h" // : CBuff
          #include "CBuffBlackArrow.h" // : CBuff
          #include "CBuffManaShield.h" // : CBuff
          #include "CBuffStampede.h" // : CBuff
          #include "CBuffIncinerate.h" // : CBuff
          #include "CBuffSoulPreservation.h" // : CBuff
          #include "CBuffCorruption.h" // : CBuff
          #include "CBuffSoulTrapVision.h" // : CBuff
          #include "CBuffItemWeb.h" // : CBuff
          #include "CBuffItemVampirePotion.h" // : CBuff
        #include "CAbilityAura.h" // : CBonusBase
          #include "CAbilityAuraBrilliance.h" // : CAbilityAura
          #include "CAbilityAuraDevotion.h" // : CAbilityAura
          #include "CAbilityAuraKotoBeast.h" // : CAbilityAura
          #include "CAbilityAuraRegenLife.h" // : CAbilityAura
          #include "CAbilityAuraRegenMana.h" // : CAbilityAura
          #include "CAbilityAuraCommand.h" // : CAbilityAura
          #include "CAbilityAuraEndurance.h" // : CAbilityAura
          #include "CAbilityAuraThorns.h" // : CAbilityAura
          #include "CAbilityAuraTrueshot.h" // : CAbilityAura
          #include "CAbilityAuraBlightRegen.h" // : CAbilityAura
          #include "CAbilityAuraPlague.h" // : CAbilityAura
          #include "CAbilityAuraUnholy.h" // : CAbilityAura
          #include "CAbilityAuraVampiric.h" // : CAbilityAura
          #include "CAbilityAuraSlow.h" // : CAbilityAura
        #include "CAbilityPersistentBonus.h" // : CBonusBase
          #include "CAbilityRegenBase.h" // : CAbilityPersistentBonus
            #include "CAbilityRegenLife.h" // : CAbilityRegenBase
              #include "CAbilityTranquilityRegen.h" // : CAbilityRegenLife
              #include "CAbilityNeutralRegenLife.h" // : CAbilityRegenLife
            #include "CAbilityRegenMana.h" // : CAbilityRegenBase
              #include "CAbilityNeutralRegenMana.h" // : CAbilityRegenMana
              #include "CAbilityItemRegenMana.h" // : CAbilityRegenMana
          #include "CAbilityAttributeBonus.h" // : CAbilityPersistentBonus
          #include "CAbilityAttackBonus.h" // : CAbilityPersistentBonus
            #include "CAbilityDamageBonusBase.h" // : CAbilityAttackBonus
              #include "CAbilityDamageBonusBaseEx.h" // : CAbilityDamageBonusBase
              #include "CAbilityCorruptionDamageBonus.h" // : CAbilityDamageBonusBase
              #include "CAbilityFireDamageBonus.h" // : CAbilityDamageBonusBase
              #include "CAbilityFreezeDamageBonus.h" // : CAbilityDamageBonusBase
              #include "CAbilityFrostDamageBonus.h" // : CAbilityDamageBonusBase
              #include "CAbilityLightningDamageBonus.h" // : CAbilityDamageBonusBase
              #include "CAbilityPoisonDamageBonus.h" // : CAbilityDamageBonusBase
              #include "CAbilitySpellEffectBonus.h" // : CAbilityDamageBonusBase
            #include "CAbilityItemSpellReduction.h" // : CAbilityAttackBonus
          #include "CAbilityAttackSpeedBonus.h" // : CAbilityPersistentBonus
          #include "CAbilityDefenseBonus.h" // : CAbilityPersistentBonus
          #include "CAbilityMaxLifeBonus.h" // : CAbilityPersistentBonus
          #include "CAbilityMaxManaBonus.h" // : CAbilityPersistentBonus
          #include "CAbilityMoveSpeedBonus.h" // : CAbilityPersistentBonus
          #include "CAbilitySightBonus.h" // : CAbilityPersistentBonus
          #include "CAbilityVampireBonus.h" // : CAbilityPersistentBonus
        #include "CAbilityInvulnerable.h" // : CBonusBase
        #include "CAbilityPermInvis.h" // : CBonusBase
          #include "CAbilityGhost.h" // : CAbilityPermInvis
          #include "CAbilityItemPermInvis.h" // : CAbilityPermInvis
        #include "CAbilitySphere.h" // : CBonusBase
        #include "CAbilitySpiked.h" // : CBonusBase
          #include "CAbilityReinforce.h" // : CAbilitySpiked
        #include "CAbilityTreeOfLife.h" // : CBonusBase
        #include "CBuffThornyShield.h" // : CBonusBase
        #include "CBuffEngineeringUpgrade.h" // : CBonusBase
        #include "CAbilityFlag.h" // : CBonusBase
          #include "CAbilityFlagHuman.h" // : CAbilityFlag
          #include "CAbilityFlagOrc.h" // : CAbilityFlag
          #include "CAbilityFlagUndead.h" // : CAbilityFlag
          #include "CAbilityFlagNightElf.h" // : CAbilityFlag
        #include "COnFireBase.h" // : CBonusBase
          #include "COnFireHumanSml.h" // : COnFireBase
          #include "COnFireHumanMed.h" // : COnFireBase
          #include "COnFireHumanLrg.h" // : COnFireBase
          #include "COnFireOrcSml.h" // : COnFireBase
          #include "COnFireOrcMed.h" // : COnFireBase
          #include "COnFireOrcLrg.h" // : COnFireBase
          #include "COnFireNightElfSml.h" // : COnFireBase
          #include "COnFireNightElfMed.h" // : COnFireBase
          #include "COnFireNightElfLrg.h" // : COnFireBase
          #include "COnFireUndeadSml.h" // : COnFireBase
          #include "COnFireUndeadMed.h" // : COnFireBase
          #include "COnFireUndeadLrg.h" // : COnFireBase
      #include "CAbilityAlarm.h" // : CAbility
      #include "CAbilityBlightGrowth.h" // : CAbility
      #include "CAbilityBlightRegen.h" // : CAbility
      #include "CAbilityCargo.h" // : CAbility
      #include "CAbilityDeathSpawn.h" // : CAbility
        #include "CAbilityDeathSpawnSpider.h" // : CAbilityDeathSpawn
        #include "CAbilityDeathSpawnSpiderling.h" // : CAbilityDeathSpawn
      #include "CAbilityGhostVisible.h" // : CAbility
      #include "CAbilityGoldMineBase.h" // : CAbility
        #include "CAbilityGoldMine.h" // : CAbilityGoldMineBase
        #include "CAbilityPossessedGoldMine.h" // : CAbilityGoldMineBase
          #include "CAbilityEntangledGoldMine.h" // : CAbilityPossessedGoldMine
          #include "CAbilityBlightedGoldMine.h" // : CAbilityPossessedGoldMine
      #include "CAbilityLightningAttack.h" // : CAbility
      #include "CAbilityLandMine.h" // : CAbility
      #include "CAbilityLeash.h" // : CAbility
      #include "CAbilityNightVision.h" // : CAbility
        #include "CAbilityUltraVision.h" // : CAbilityNightVision
      #include "CAbilityNotifyDamage.h" // : CAbility
      #include "CAbilityOnFire.h" // : CAbility
        #include "CAbilityOnFireHuman.h" // : CAbilityOnFire
        #include "CAbilityOnFireOrc.h" // : CAbilityOnFire
        #include "CAbilityOnFireNightElf.h" // : CAbilityOnFire
        #include "CAbilityOnFireUndead.h" // : CAbilityOnFire
      #include "CAbilityPurchaseItem.h" // : CAbility
      #include "CAbilityRescuable.h" // : CAbility
      #include "CAbilityReturn.h" // : CAbility
      #include "CAbilitySleepAlways.h" // : CAbility
        #include "CAbilityCreepSleep.h" // : CAbilitySleepAlways
      #include "CAbilityTarget.h" // : CAbility
      #include "CAbilityWander.h" // : CAbility
        #include "CAbilityTornadoWander.h" // : CAbilityWander
      #include "CAbilityWarp.h" // : CAbility
      #include "CBuffTeleportReveal.h" // : CAbility
      #include "CAbilityTankTurret.h" // : CAbility
      #include "CAbilityChaosBase.h" // : CAbility
        #include "CAbilityChaos.h" // : CAbilityChaosBase
        #include "CAbilityChaosCargoLoad.h" // : CAbilityChaosBase
      #include "CAbilityDeathDamageAoe.h" // : CAbility
      #include "CAbilityStarfallDrain.h" // : CAbility
        #include "CAbilityMonsoonDrain.h" // : CAbilityStarfallDrain
      #include "CAbilityFrostBreath.h" // : CAbility
      #include "CAbilityGraveyard.h" // : CAbility
      #include "CAbilityGraveyardCorpse.h" // : CAbility
      #include "CAbilitySpiderAttack.h" // : CAbility
      #include "CAbilityLocust.h" // : CAbility
      #include "CAbilityNeutral.h" // : CAbility
        #include "CAbilityAllied.h" // : CAbilityNeutral
      #include "CAbilityNeutralRegen.h" // : CAbility
      #include "CAbilityTornadoDamage.h" // : CAbility
      #include "CAbilityTornadoSpin.h" // : CAbility
      #include "CAbilityItemReincarnation.h" // : CAbility
      #include "CAbilitySoulTrapped.h" // : CAbility
  #include "COrder.h" // : CAgentWar3
    #include "COrderPoint.h" // : COrder
      #include "COrderPoint2.h" // : COrderPoint
      #include "COrderTarget.h" // : COrderPoint
        #include "COrderTarget2.h" // : COrderTarget
    #include "COrderTrainCancel.h" // : COrder
    #include "COrderReviveCancel.h" // : COrder
  #include "CAnimScaler.h" // : CAgentWar3
  #include "CEffectBlight.h" // : CAgentWar3
  #include "CEffectBlizzard.h" // : CAgentWar3
    #include "CEffectRainOfFire.h" // : CEffectBlizzard
  #include "CEffectEarthquake.h" // : CAgentWar3
  #include "CEffectReincarnation.h" // : CAgentWar3
  #include "CEffectRainOfChaos.h" // : CAgentWar3
  #include "CEffectItemChangeTOD.h" // : CAgentWar3
  #include "CPlayerUpgrade.h" // : CAgentWar3
  #include "CUpgradeEffect.h" // : CAgentWar3
    #include "CUpgradeAddTechMaxAllowed.h" // : CUpgradeEffect
    #include "CUpgradeAddUltraVision.h" // : CUpgradeEffect
    #include "CUpgradeArmor.h" // : CUpgradeEffect
    #include "CUpgradeArmorType.h" // : CUpgradeEffect
    #include "CUpgradeAttack.h" // : CUpgradeEffect
    #include "CUpgradeAttackEx.h" // : CUpgradeEffect
    #include "CUpgradeAttackDamageLoss.h" // : CUpgradeEffect
    #include "CUpgradeAttackDice.h" // : CUpgradeEffect
    #include "CUpgradeAttackRange.h" // : CUpgradeEffect
    #include "CUpgradeAttackSpeed.h" // : CUpgradeEffect
    #include "CUpgradeAttackSpillDistance.h" // : CUpgradeEffect
    #include "CUpgradeAttackSpillRadius.h" // : CUpgradeEffect
    #include "CUpgradeAttackTargetCount.h" // : CUpgradeEffect
    #include "CUpgradeAuraData.h" // : CUpgradeEffect
    #include "CUpgradeEnableWeapon.h" // : CUpgradeEffect
    #include "CUpgradeEntangle.h" // : CUpgradeEffect
    #include "CUpgradeHitPoints.h" // : CUpgradeEffect
    #include "CUpgradeHitPointsEx.h" // : CUpgradeEffect
    #include "CUpgradeHitPointsRegen.h" // : CUpgradeEffect
    #include "CUpgradeLumberJack.h" // : CUpgradeEffect
    #include "CUpgradeMagicImmunity.h" // : CUpgradeEffect
    #include "CUpgradeMana.h" // : CUpgradeEffect
    #include "CUpgradeManaEx.h" // : CUpgradeEffect
    #include "CUpgradeManaRegen.h" // : CUpgradeEffect
    #include "CUpgradeMining.h" // : CUpgradeEffect
    #include "CUpgradeMove.h" // : CUpgradeEffect
    #include "CUpgradeMoveEx.h" // : CUpgradeEffect
    #include "CUpgradeRaiseDead.h" // : CUpgradeEffect
    #include "CUpgradeRootWeapons.h" // : CUpgradeEffect
    #include "CUpgradeSight.h" // : CUpgradeEffect
    #include "CUpgradeSpell.h" // : CUpgradeEffect
    #include "CUpgradeSpikes.h" // : CUpgradeEffect
    #include "CUpgradeUprootWeapons.h" // : CUpgradeEffect
  #include "CEffectProcedural.h" // : CAgentWar3
    #include "CEffectHeroDissipate.h" // : CEffectProcedural
  #include "CChangeMask.h" // : CAgentWar3
    #include "CMaskDetect.h" // : CChangeMask
      #include "CEffectSentinel.h" // : CMaskDetect
  #include "CDelayedAreaDamage.h" // : CAgentWar3
  #include "CDetectedData.h" // : CAgentWar3
  #include "CSharedVisionData.h" // : CAgentWar3
  #include "CRope.h" // : CAgentWar3
    #include "CMissileLightningAttack.h" // : CRope
    #include "CMissileSpiritLink.h" // : CRope
    #include "CEffectChainLightning.h" // : CRope
    #include "CMissileManaFlare.h" // : CRope
    #include "CMissileManaBurn.h" // : CRope
    #include "CMissileDrain.h" // : CRope
    #include "CMissileForkedLightning.h" // : CRope
    #include "CRopeBase.h" // : CRope
  #include "CCompAI.h" // : CAgentWar3
  #include "CUnitAI.h" // : CAgentWar3
  #include "CTownSpot.h" // : CAgentWar3
  #include "CCreepSpot.h" // : CAgentWar3
  #include "CGuardPost.h" // : CAgentWar3
  #include "CThreadAI.h" // : CAgentWar3
  #include "CRectWar3.h" // : CAgentWar3
  #include "CCameraSetup.h" // : CAgentWar3
  #include "CMapLocation.h" // : CAgentWar3
  #include "CGameState.h" // : CAgentWar3
  #include "CAlliances.h" // : CAgentWar3
  #include "CPlayerWar3.h" // : CAgentWar3
  #include "CJassFunc.h" // : CAgentWar3
  #include "CBooleanExpr.h" // : CAgentWar3
    #include "CBooleanBinaryOp.h" // : CBooleanExpr
      #include "CBooleanAnd.h" // : CBooleanBinaryOp
      #include "CBooleanOr.h" // : CBooleanBinaryOp
    #include "CBooleanNot.h" // : CBooleanExpr
    #include "CFilterFunc.h" // : CBooleanExpr
  #include "CGroup.h" // : CAgentWar3
  #include "CForce.h" // : CAgentWar3
  #include "CTimerWar3.h" // : CAgentWar3
  #include "CTimelineRecorder.h" // : CAgentWar3
  #include "CTriggerWar3.h" // : CAgentWar3
  #include "CTriggerCondition.h" // : CAgentWar3
  #include "CTriggerAction.h" // : CAgentWar3
  #include "CTriggerExecution.h" // : CAgentWar3
  #include "CEventRegWar3.h" // : CAgentWar3
    #include "CDeathEventReg.h" // : CEventRegWar3
    #include "CGameEventReg.h" // : CEventRegWar3
    #include "CPlayerEventReg.h" // : CEventRegWar3
      #include "CPlayerStateEventReg.h" // : CPlayerEventReg
      #include "CPlayerChatEventReg.h" // : CPlayerEventReg
    #include "CUnitEventReg.h" // : CEventRegWar3
      #include "CUnitStateEventReg.h" // : CUnitEventReg
    #include "CRangeEventReg.h" // : CEventRegWar3
    #include "CVariableEventReg.h" // : CEventRegWar3
      #include "CStateEventReg.h" // : CVariableEventReg
        #include "CIntegerEventReg.h" // : CStateEventReg
          #include "CAllianceEventReg.h" // : CIntegerEventReg
          #include "CIntegerGameStateEventReg.h" // : CIntegerEventReg
        #include "CFloatEventReg.h" // : CStateEventReg
          #include "CFloatGameStateEventReg.h" // : CFloatEventReg
    #include "CTimerEventReg.h" // : CEventRegWar3
    #include "CTimerExpireEventReg.h" // : CEventRegWar3
    #include "CRegionEventReg.h" // : CEventRegWar3
    #include "CTrackableEventReg.h" // : CEventRegWar3
    #include "CDialogButtonEventReg.h" // : CEventRegWar3
    #include "CDialogEventReg.h" // : CEventRegWar3
  #include "CSoundWar3.h" // : CAgentWar3
  #include "CQuestManager.h" // : CAgentWar3
  #include "CQuest.h" // : CAgentWar3
  #include "CQuestItem.h" // : CAgentWar3
    #include "CDefeatCondition.h" // : CQuestItem
  #include "CTimerDialogWar3.h" // : CAgentWar3
  #include "CDialogButton.h" // : CAgentWar3
  #include "CScriptDialogWar3.h" // : CAgentWar3
  #include "CLeaderboardWar3.h" // : CAgentWar3
  #include "CGameCache.h" // : CAgentWar3
  #include "CGameHashTable.h" // : CAgentWar3
  #include "CGameCacheManager.h" // : CAgentWar3
  #include "CMultiboardWar3.h" // : CAgentWar3
  #include "CMultiboardItemWar3.h" // : CAgentWar3
#include "CFogModifier.h" // : CAgent
  #include "CFogModifierTimed.h" // : CFogModifier
#include "CCameraWar3.h" // : CAgent
#include "CUnitPool.h" // : CAgent
#include "CItemPool.h" // : CAgent
#include "CScriptEventData.h" // : CAgent
  #include "CUnitEventDataBase.h" // : CScriptEventData
    #include "CUnitStateLimitEventData.h" // : CUnitEventDataBase
    #include "CUnitDamagedEventData.h" // : CUnitEventDataBase
    #include "CUnitDecayEventData.h" // : CUnitEventDataBase
    #include "CUnitSelectedEventData.h" // : CUnitEventDataBase
    #include "CUnitDeselectedEventData.h" // : CUnitEventDataBase
    #include "CUnitConstructEventDataBase.h" // : CUnitEventDataBase
      #include "CUnitConstructCancelEventData.h" // : CUnitConstructEventDataBase
      #include "CUnitConstructFinishEventData.h" // : CUnitConstructEventDataBase
    #include "CUnitUpgradeEventDataBase.h" // : CUnitEventDataBase
      #include "CUnitUpgradeStartEventData.h" // : CUnitUpgradeEventDataBase
      #include "CUnitUpgradeCancelEventData.h" // : CUnitUpgradeEventDataBase
      #include "CUnitUpgradeFinishEventData.h" // : CUnitUpgradeEventDataBase
    #include "CUnitResearchEventDataBase.h" // : CUnitEventDataBase
      #include "CUnitResearchStartEventData.h" // : CUnitResearchEventDataBase
      #include "CUnitResearchCancelEventData.h" // : CUnitResearchEventDataBase
      #include "CUnitResearchFinishEventData.h" // : CUnitResearchEventDataBase
    #include "CUnitDetectedEventData.h" // : CUnitEventDataBase
    #include "CUnitHiddenEventData.h" // : CUnitEventDataBase
    #include "CUnitEventOtherUnitDataBase.h" // : CUnitEventDataBase
      #include "CUnitDeathEventData.h" // : CUnitEventOtherUnitDataBase
      #include "CUnitRescueEventData.h" // : CUnitEventOtherUnitDataBase
      #include "CUnitAcquireEventData.h" // : CUnitEventOtherUnitDataBase
        #include "CUnitInRangeEventData.h" // : CUnitAcquireEventData
      #include "CUnitAttackedEventData.h" // : CUnitEventOtherUnitDataBase
      #include "CUnitTrainEventDataBase.h" // : CUnitEventOtherUnitDataBase
        #include "CUnitTrainStartEventData.h" // : CUnitTrainEventDataBase
          #include "CUnitTrainCancelEventData.h" // : CUnitTrainStartEventData
        #include "CUnitTrainFinishEventData.h" // : CUnitTrainEventDataBase
      #include "CUnitOrderEventData.h" // : CUnitEventOtherUnitDataBase
        #include "CUnitOrderPointEventData.h" // : CUnitOrderEventData
          #include "CUnitOrderTargetEventData.h" // : CUnitOrderPointEventData
      #include "CUnitSummonedEventData.h" // : CUnitEventOtherUnitDataBase
      #include "CUnitSellEventData.h" // : CUnitEventOtherUnitDataBase
      #include "CUnitSellItemEventData.h" // : CUnitEventOtherUnitDataBase
    #include "CUnitSpellEventDataBase.h" // : CUnitEventDataBase
    #include "CUnitEventHeroSkillData.h" // : CUnitEventDataBase
    #include "CUnitLoadEventData.h" // : CUnitEventDataBase
    #include "CUnitItemEventData.h" // : CUnitEventDataBase
    #include "CUnitChangeOwnerEventData.h" // : CUnitEventDataBase
  #include "CDeathEventData.h" // : CScriptEventData
  #include "CTimerExpireEventData.h" // : CScriptEventData
  #include "CPlayerEventDataBase.h" // : CScriptEventData
    #include "CPlayerStateLimitEventData.h" // : CPlayerEventDataBase
    #include "CPlayerDefeatEventData.h" // : CPlayerEventDataBase
    #include "CPlayerVictoryEventData.h" // : CPlayerEventDataBase
    #include "CPlayerLeaveEventData.h" // : CPlayerEventDataBase
    #include "CPlayerEndCinematicData.h" // : CPlayerEventDataBase
    #include "CPlayerChatMatchEventData.h" // : CPlayerEventDataBase
    #include "CPlayerUnitEventDataBase.h" // : CPlayerEventDataBase
      #include "CPlayerUnitAttackedEventData.h" // : CPlayerUnitEventDataBase
      #include "CPlayerUnitDeathEventData.h" // : CPlayerUnitEventDataBase
      #include "CPlayerUnitDecayEventData.h" // : CPlayerUnitEventDataBase
      #include "CPlayerUnitSelectedEventData.h" // : CPlayerUnitEventDataBase
      #include "CPlayerUnitDeselectedEventData.h" // : CPlayerUnitEventDataBase
      #include "CPlayerUnitDetectedEventData.h" // : CPlayerUnitEventDataBase
      #include "CPlayerUnitHiddenEventData.h" // : CPlayerUnitEventDataBase
      #include "CPlayerUnitConstructStartEventData.h" // : CPlayerUnitEventDataBase
      #include "CPlayerUnitConstructFinishEventData.h" // : CPlayerUnitEventDataBase
      #include "CPlayerUnitConstructCancelEventData.h" // : CPlayerUnitEventDataBase
      #include "CPlayerUnitUpgradeEventDataBase.h" // : CPlayerUnitEventDataBase
        #include "CPlayerUnitUpgradeStartEventData.h" // : CPlayerUnitUpgradeEventDataBase
        #include "CPlayerUnitUpgradeFinishEventData.h" // : CPlayerUnitUpgradeEventDataBase
        #include "CPlayerUnitUpgradeCancelEventData.h" // : CPlayerUnitUpgradeEventDataBase
      #include "CPlayerUnitTrainEventDataBase.h" // : CPlayerUnitEventDataBase
        #include "CPlayerUnitTrainStartEventData.h" // : CPlayerUnitTrainEventDataBase
          #include "CPlayerUnitTrainCancelEventData.h" // : CPlayerUnitTrainStartEventData
          #include "CPlayerUnitTrainFinishEventData.h" // : CPlayerUnitTrainStartEventData
      #include "CPlayerUnitOrderEventData.h" // : CPlayerUnitEventDataBase
        #include "CPlayerUnitPointOrderEventData.h" // : CPlayerUnitOrderEventData
        #include "CPlayerUnitTargetOrderEventData.h" // : CPlayerUnitOrderEventData
      #include "CPlayerUnitSpellEventDataBase.h" // : CPlayerUnitEventDataBase
      #include "CPlayerUnitResearchEventDataBase.h" // : CPlayerUnitEventDataBase
        #include "CPlayerUnitResearchStartEventData.h" // : CPlayerUnitResearchEventDataBase
        #include "CPlayerUnitResearchCancelEventData.h" // : CPlayerUnitResearchEventDataBase
        #include "CPlayerUnitResearchFinishEventData.h" // : CPlayerUnitResearchEventDataBase
      #include "CPlayerUnitSummonedEventData.h" // : CPlayerUnitEventDataBase
      #include "CPlayerUnitItemEventData.h" // : CPlayerUnitEventDataBase
      #include "CPlayerUnitLoadedEventData.h" // : CPlayerUnitEventDataBase
      #include "CPlayerHeroSkillEventData.h" // : CPlayerUnitEventDataBase
      #include "CPlayerUnitRescuedEventData.h" // : CPlayerUnitEventDataBase
      #include "CPlayerUnitSellEventData.h" // : CPlayerUnitEventDataBase
      #include "CPlayerUnitSellItemEventData.h" // : CPlayerUnitEventDataBase
      #include "CPlayerUnitChangeOwnerEventData.h" // : CPlayerUnitEventDataBase
  #include "CDialogButtonClickEventData.h" // : CScriptEventData
  #include "CDialogClickEventData.h" // : CScriptEventData
  #include "CTournamentFinishSoonEventData.h" // : CScriptEventData
  #include "CTournamentFinishNowEventData.h" // : CScriptEventData
  #include "CGameSaveEventData.h" // : CScriptEventData
